BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Student] (
    [id] NVARCHAR(1000) NOT NULL,
    [name] NVARCHAR(1000) NOT NULL,
    [age] INT NOT NULL,
    [parentName] NVARCHAR(1000) NOT NULL,
    [parentEmail] NVARCHAR(1000) NOT NULL,
    [notified] BIT NOT NULL CONSTRAINT [Student_notified_df] DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Student_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Student_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
